# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog4(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1220, 830)
        Dialog.setStyleSheet("\n"
                             "\n"
                             "background-color: rgb(255, 247, 239);")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 201, 1191))
        self.widget.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0.0547264, y1:0.063, x2:1, y2:1, stop:0 rgba(80, 242, 196, 255), stop:1 rgba(117, 122, 255, 255));")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(240, 0, 501, 121))
        self.label.setStyleSheet("font-size: 50px;\n"
                                 "font: bold;\n"
                                 "color: rgb(122, 222, 222);\n"
                                 "color: rgb(12, 151, 151);")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(230, 200, 791, 581))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.gotolearn = QtWidgets.QPushButton(Dialog)
        self.gotolearn.setGeometry(QtCore.QRect(230, 130, 241, 61))
        self.gotolearn.setObjectName("gotolearn")
        self.changeprofile = QtWidgets.QPushButton(Dialog)
        self.changeprofile.setGeometry(QtCore.QRect(1080, 20, 121, 28))
        self.changeprofile.setObjectName("changeprofile")
        self.gotorem = QtWidgets.QPushButton(Dialog)
        self.gotorem.setGeometry(QtCore.QRect(490, 130, 241, 61))
        self.gotorem.setObjectName("gotorem")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", " Английские слова"))
        self.gotolearn.setText(_translate("Dialog", "Перейти к изучению"))
        self.changeprofile.setText(_translate("Dialog", "Сменить аккаунт"))
        self.gotorem.setText(_translate("Dialog", "Повторить изученные слова"))
