# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog6(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1177, 731)
        Dialog.setStyleSheet("\n"
                             "background-color: rgb(238, 238, 238);\n"
                             "background-color: rgb(255, 247, 239);")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(0, -320, 201, 1241))
        self.widget_2.setStyleSheet("\n"
                                    "background-color: qlineargradient(spread:pad, x1:0.0547264, y1:0.063, x2:1, y2:1, stop:0 rgba(80, 242, 196, 255), stop:1 rgba(117, 122, 255, 255));")
        self.widget_2.setObjectName("widget_2")
        self.gotolearn2 = QtWidgets.QPushButton(Dialog)
        self.gotolearn2.setEnabled(True)
        self.gotolearn2.setGeometry(QtCore.QRect(230, 20, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gotolearn2.setFont(font)
        self.gotolearn2.setObjectName("gotolearn2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(220, 90, 951, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.que = QtWidgets.QLabel(Dialog)
        self.que.setGeometry(QtCore.QRect(270, 350, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.que.setFont(font)
        self.que.setText("")
        self.que.setObjectName("que")
        self.ans = QtWidgets.QLineEdit(Dialog)
        self.ans.setEnabled(True)
        self.ans.setGeometry(QtCore.QRect(460, 360, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ans.setFont(font)
        self.ans.setObjectName("ans")
        self.toans = QtWidgets.QPushButton(Dialog)
        self.toans.setEnabled(False)
        self.toans.setGeometry(QtCore.QRect(740, 360, 161, 51))
        self.toans.setObjectName("toans")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(280, 440, 661, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(490, 320, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.starttest = QtWidgets.QPushButton(Dialog)
        self.starttest.setGeometry(QtCore.QRect(480, 170, 181, 71))
        self.starttest.setStyleSheet("\n"
                                     "background-color: rgb(40, 225, 0);")
        self.starttest.setObjectName("starttest")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.gotolearn2.setText(_translate("Dialog", "Вернуться к изучению"))
        self.label.setText(_translate("Dialog",
                                      "    Будьте осторожны, при переходе на предыдущую страницу данные неправильно сделанного теста НЕ сохраняются"))
        self.toans.setText(_translate("Dialog", "Ответить"))
        self.label_3.setText(_translate("Dialog", "Введите перевод"))
        self.starttest.setText(_translate("Dialog", "Начать тест"))
