# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remember.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog8(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1220, 830)
        Dialog.setStyleSheet("background-color: rgb(255, 247, 239);\n"
                             "")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 201, 1191))
        self.widget.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0.0547264, y1:0.063, x2:1, y2:1, stop:0 rgba(80, 242, 196, 255), stop:1 rgba(117, 122, 255, 255));")
        self.widget.setObjectName("widget")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(230, 170, 791, 581))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.gotomain = QtWidgets.QPushButton(Dialog)
        self.gotomain.setGeometry(QtCore.QRect(230, 20, 191, 51))
        self.gotomain.setObjectName("gotomain")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(230, 90, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.updateb = QtWidgets.QPushButton(Dialog)
        self.updateb.setGeometry(QtCore.QRect(230, 120, 171, 41))
        self.updateb.setObjectName("updateb")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.gotomain.setText(_translate("Dialog", "На главную"))
        self.label.setText(_translate("Dialog", "Здесь находятся слова, которые Вы изучили, пройдя тест"))
        self.updateb.setText(_translate("Dialog", "Обновить"))
