# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registerwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog3(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1220, 830)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1241, 841))
        self.widget.setStyleSheet("QWidget#widget{\n"
                                  "background-color: qlineargradient(spread:pad, x1:0.0547264, y1:0.063, x2:1, y2:1, stop:0 rgba(80, 242, 196, 255), stop:1 rgba(117, 122, 255, 255));}")
        self.widget.setObjectName("widget")
        self.logup_b = QtWidgets.QPushButton(self.widget)
        self.logup_b.setGeometry(QtCore.QRect(490, 550, 231, 61))
        self.logup_b.setStyleSheet("\n"
                                   "font: 14pt \"Calibri\";\n"
                                   "background-color: rgb(93, 255, 255);")
        self.logup_b.setObjectName("logup_b")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(430, 100, 351, 101))
        self.label.setStyleSheet("font: 40pt \"calibri\";\n"
                                 "color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.loginline = QtWidgets.QLineEdit(self.widget)
        self.loginline.setGeometry(QtCore.QRect(480, 270, 251, 51))
        self.loginline.setObjectName("loginline")
        self.passwordline = QtWidgets.QLineEdit(self.widget)
        self.passwordline.setGeometry(QtCore.QRect(480, 374, 251, 51))
        self.passwordline.setObjectName("passwordline")
        self.passwordlinecon = QtWidgets.QLineEdit(self.widget)
        self.passwordlinecon.setGeometry(QtCore.QRect(480, 464, 251, 51))
        self.passwordlinecon.setObjectName("passwordlinecon")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(480, 250, 61, 20))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(480, 350, 111, 20))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(480, 440, 191, 20))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.errortext = QtWidgets.QLabel(self.widget)
        self.errortext.setGeometry(QtCore.QRect(480, 520, 331, 16))
        self.errortext.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
                                     "color: rgb(189, 0, 0)")
        self.errortext.setText("")
        self.errortext.setObjectName("errortext")
        self.back = QtWidgets.QPushButton(self.widget)
        self.back.setGeometry(QtCore.QRect(10, 10, 141, 31))
        self.back.setStyleSheet("\n"
                                "font: 11pt \"Calibri\";\n"
                                "background-color: rgb(93, 255, 255);")
        self.back.setObjectName("back")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.logup_b.setText(_translate("Dialog", "Зарегистрироваться"))
        self.label.setText(_translate("Dialog", "Регистрация"))
        self.label_2.setText(_translate("Dialog", "Логин:"))
        self.label_3.setText(_translate("Dialog", "Ваш пароль:"))
        self.label_4.setText(_translate("Dialog", "Подтверждение пароля:"))
        self.back.setText(_translate("Dialog", "Назад"))
