# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog5(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1088, 899)
        Dialog.setStyleSheet("\n"
                             "background-color: rgb(238, 238, 238);\n"
                             "background-color: rgb(255, 247, 239);")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(0, -20, 201, 1401))
        self.widget_2.setStyleSheet("\n"
                                    "background-color: qlineargradient(spread:pad, x1:0.0547264, y1:0.063, x2:1, y2:1, stop:0 rgba(80, 242, 196, 255), stop:1 rgba(117, 122, 255, 255));")
        self.widget_2.setObjectName("widget_2")
        self.gotomain = QtWidgets.QPushButton(Dialog)
        self.gotomain.setGeometry(QtCore.QRect(210, 10, 241, 111))
        self.gotomain.setObjectName("gotomain")
        self.loadwordsbutton = QtWidgets.QPushButton(Dialog)
        self.loadwordsbutton.setGeometry(QtCore.QRect(510, 140, 161, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.loadwordsbutton.setFont(font)
        self.loadwordsbutton.setObjectName("loadwordsbutton")
        self.tableWidget2 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget2.setGeometry(QtCore.QRect(220, 260, 781, 411))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget2.setFont(font)
        self.tableWidget2.setAutoScrollMargin(3)
        self.tableWidget2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget2.setTabKeyNavigation(False)
        self.tableWidget2.setProperty("showDropIndicator", False)
        self.tableWidget2.setDragDropOverwriteMode(False)
        self.tableWidget2.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget2.setColumnCount(3)
        self.tableWidget2.setObjectName("tableWidget2")
        self.tableWidget2.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(220, 140, 261, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.spinBox.setFont(font)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(100)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setDisplayIntegerBase(10)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.gototest = QtWidgets.QPushButton(Dialog)
        self.gototest.setGeometry(QtCore.QRect(220, 730, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gototest.setFont(font)
        self.gototest.setObjectName("gototest")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(230, 790, 361, 21))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.gotomain.setText(_translate("Dialog", "Вернуться на главную"))
        self.loadwordsbutton.setText(_translate("Dialog", "Сгенерировать"))
        self.label.setText(_translate("Dialog", "Количество слов:"))
        self.gototest.setText(_translate("Dialog", "Пройти тест"))
